# Generated by Django 5.0.1 on 2024-02-07 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('passing', 'Passing'), ('guard', 'Guard'), ('submission', 'Submission'), ('takedown', 'Takedown')], max_length=20)),
                ('privacy_status', models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('public', 'Public')], max_length=20)),
                ('video_option', models.CharField(choices=[('full', 'Full Youtube Video'), ('cropped', 'Crop Short Clip from Youtube Video')], max_length=10)),
                ('youtube_url', models.URLField()),
                ('start_time', models.PositiveIntegerField(blank=True, null=True)),
                ('end_time', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
