# Generated by Django 5.0.2 on 2024-02-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0003_technique_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='category',
            field=models.CharField(choices=[('passing', 'Passing'), ('guard', 'Guard'), ('submission', 'Submission'), ('takedown', 'Takedown'), ('counter', 'Defense/Counter'), ('escape', 'Escape')], max_length=20),
        ),
    ]
