# Generated by Django 5.0.2 on 2024-02-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0005_alter_technique_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='embed_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
