# Generated by Django 5.0.2 on 2024-02-11 19:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0006_technique_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='keywords',
            field=models.CharField(max_length=50, blank=True, null=True),
            # field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
