# Generated by Django 5.0.2 on 2024-02-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0007_technique_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
