# Generated by Django 5.0.2 on 2024-02-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0008_alter_technique_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='athlete',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
