# Generated by Django 5.0.2 on 2024-02-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0009_technique_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='privacy_status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], max_length=20),
        ),
    ]
