# Generated by Django 5.0.2 on 2024-02-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0010_alter_technique_privacy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='category',
            field=models.CharField(choices=[('passing', 'Passing'), ('guard', 'Guard'), ('submission', 'Submission'), ('takedown', 'Takedown'), ('guard-pull', 'Guard Pull'), ('counter', 'Defense/Counter'), ('escape', 'Escape'), ('other', 'Other')], max_length=20),
        ),
    ]
