# Generated by Django 5.0.2 on 2024-07-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniques', '0011_alter_technique_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='privacy_status',
            field=models.CharField(choices=[('private', 'Private')], max_length=20),
        ),
    ]
